name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: Windows 11
    steps:
      - name: Say hello
        run: |
          echo "Hello World! Run from GitHub Actions!"