name: Scheduler
on:
  schedule:
    - cron: '* 20 * * 1'
    - cron: '* 20 * * 2'
    - cron: '* 20 * * 3'
    - cron: '* 20 * * 4'
    - cron: '* 20 * * 5'
jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
      - name: Thursday 20:XX Tick
        if: github.event.schedule != '* 20 * * 4'
        run: echo "Thursday 20:XX Tick"